### PR TITLE
Deploy dnsmasq on all nodes

### PR DESCRIPTION
**Pull request by mjura**
It can be merged after https://github.com/crowbar/barclamp-dns/pull/121

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM, but untested

**Comment by vuntz** [comment]
Why do we need it on the admin server?

**Comment by mjura** [comment]
> Why do we need it on the admin server?
In case when master DNS server will crush, dnsmasq will work fine, without any delay and 5 sec suspends.

**Comment by vuntz** [comment]
@mjura but we are a dns server already so we can reply to our own requests, so why would we need dnsmasq?

**Comment by mjura** [comment]
@vuntz Lets say that we have deployed 3 dns servers, primary dns server role will be taken by admin node and two secondaries will be allocated on compute nodes. 
Resolv.conf on admin server will looks like follows
```
nameserver admin.crowbar.dev
nameserver compute1.crowbar.dev
nameserver compute2.crowbar.dev
```
if bind9 service will fail on admin node, then we will have situation from bnc#901497. In my opinion dnsmasq should be installed on all nodes in the cloud including dns-servers.

Do you think that we shouldn't install dnsmasq on dns-servers? or only on admin server?

**Comment by vuntz** [comment]
@mjura: surely the bug is that if a node is dns-server, then it should be listed first in resolv.conf :-)

**Comment by vuntz** [comment]
Sorry, I wasn't clear, so just to clarify: "it should be listed first in *its* resolv.conf"

**Comment by mjura** [comment]
> Sorry, I wasn't clear, so just to clarify: "it should be listed first in its resolv.conf"

On first place it should be alwasy local address which will be dnsmasq. If we put on first place other dns nameserver,  it can fail. Dnsmasq listen on local address of physical server is common configuration for hosting companies like OVH or Hetzner.

**Comment by vuntz** [comment]
After discussing with @mjura, I agreed his way is better than mine because the setup is consistent on all nodes.

**Pull request merged**
